[package]
name = "machiavelli"
version = "0.2.9"
authors = ["Florent C. L. M. Michel <56166507+FlorentCLMichel@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9"
ctrlc = { version = "3.0", features = ["termination"] }
